apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-conductor
  template:
    metadata:
      labels:
        app: test-conductor
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        env:
           - name: testconductor.environment
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrTestConductorEnvironment
           - name: spring.profiles.active
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrSpringProfilesActive
           - name: client.jdbc.postgres.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresUrl
           - name: client.jdbc.postgres.username
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresUserName
           - name: client.jdbc.postgres.password
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresPassword
           - name: elasticsearch.init
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchInit
           - name: elasticsearch.disable
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchDisable
           - name: elasticsearch.scheme
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchScheme
           - name: elasticsearch.host
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchHost
           - name: elasticsearch.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchPort
           - name: attachment.folder.path
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAttachmentFolderPath
           - name: blobStorage.type
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageType
           - name: blobStorage.region
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageRegion
           - name: blobStorage.sharedBucket
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageSharedBucket
           - name: s3.accessKey
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3AccessKey
           - name: s3.secretKey
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3SecretKey
           - name: s3.folder
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3Folder
           - name: s3.scan.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3ScanUrl
           - name: server.app.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerAppUrl
           - name: serverapp.useSecureCookie
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerappUseSecureCookie
           - name: serverapp.ssl.required
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerAppSSLRequired
           - name: base.http.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBaseHttpPort
           - name: base.https.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBaseHttpsPort
           - name: preUrl
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreUrl
           - name: preUrl.https
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreUrlHttps
           - name: qasymphonyUrlPostfix
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQasymphonyUrlPostfix
           - name: qas.directory.address
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQasDirectoryAddress
           - name: qTest.instance
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQTestInstance
           - name: qTest.app.version
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQTestAppVersion
           - name: app.name
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAppName
           - name: analytics.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAnalyticsUrlBase
           - name: kafka.bootstrapAddress
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrKafkaBootstrapAddress
           - name: kafka.schemaRegistryUrl
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrKafkaSchemaRegistryUrl
           - name: pre.session.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreSessionUrl
           - name: pulse.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPulseUrlBase
           - name: insights.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrInsightsUrl
           - name: launch.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrLaunchUrlBase
           - name: notification.url.external
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrNotificationUrlExternal
           - name: notification.url.internal
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrNotificationUrlInternal
           - name: qtest.servermap.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQtestServerMapUrl
           - name: report.http.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrReportHttpUrl
           - name: report.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrReportUrl
           - name: tdm.setting.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrTdmSettingUrl
           - name: mail.host
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailHost
           - name: mail.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailPort
           - name: mail.username
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailUserName
           - name: mail.password
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailPassword
           - name: mail.protocol
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailProtocol
           - name: mail.smtp.auth
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailSmtpAuth
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http               
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      volumes:
      - name: qtest-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.secret }}