{{- if .Values.deployments.enabled -}}
{{- $existingImageCredentials := .Values.secrets.existingImageCredentials -}}
{{- $imageCredentials := .Values.imageCredentials.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas.ui }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
        - name: {{ $existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
        - name: {{ $imageCredentials }}
      {{- end }}
      serviceAccountName: {{ template "qtest-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountsatoken }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        livenessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          failureThreshold: 60
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: qtest-manager-config
        - secretRef:
            name: qtest-manager-secret
        env:
        {{- if .Values.env }}
{{- toYaml .Values.env | nindent 11 }}
        {{- end }}
           - name: testconductor.environment
             value: "ui.production"
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-agent
        image: signalsciences/sigsci-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: SIGSCI_ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: accesskeyid
        - name: SIGSCI_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: secretaccesskey
        # Configure the revproxy listener to listen on the original web application port 8000
        # forwarding to the app on the alternate port 8001 as the upstream
        - name: SIGSCI_REVPROXY_LISTENER
          value: "http:{listener='http://0.0.0.0:{{ .Values.service.targetSigSciPort }}',upstreams='http://127.0.0.1:{{ .Values.service.targetPort }}',access-log='/dev/stdout'}"
        ports:
        - containerPort: {{ .Values.service.targetSigSciPort }}
        securityContext:
          # The sigsci-agent container should run with its root filesystem read only
          readOnlyRootFilesystem: true
        volumeMounts:
        # Default volume mount location for sigsci-agent writeable data
        # NOTE: Also change `SIGSCI_SHARED_CACHE_DIR` (default `/sigsci/tmp/cache`)
        #       if mountPath is changed, but best not to change.
        - name: sigsci-tmp
          mountPath: /sigsci/tmp
      {{- end }}
      volumes:
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-tmp
      {{- end }}
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment-poller
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr-poller
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas.poller }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr-poller
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr-poller
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
      - name: {{ .Values.secrets.existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      serviceAccountName: {{ template "qtest-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountsatoken }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        livenessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          failureThreshold: 60
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: qtest-manager-config
        - secretRef:
            name: qtest-manager-secret
        env:
        {{- if .Values.env }}
{{- toYaml .Values.env | nindent 11 }}
        {{- end }}
           - name: testconductor.environment
             value: "poller.production"
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      volumes:
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment-notification
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr-notification
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas.notification }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr-notification
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr-notification
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
      - name: {{ .Values.secrets.existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      serviceAccountName: {{ template "qtest-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountsatoken }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        livenessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          failureThreshold: 60
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: qtest-manager-config
        - secretRef:
            name: qtest-manager-secret
        env:
        {{- if .Values.env }}
{{- toYaml .Values.env | nindent 11 }}
        {{- end }}
           - name: testconductor.environment
             value: "notification.production"
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-agent
        image: signalsciences/sigsci-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: SIGSCI_ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: accesskeyid
        - name: SIGSCI_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: secretaccesskey
        # Configure the revproxy listener to listen on the original web application port 8000
        # forwarding to the app on the alternate port 8001 as the upstream
        - name: SIGSCI_REVPROXY_LISTENER
          value: "http:{listener='http://0.0.0.0:{{ .Values.service.targetSigSciPort }}',upstreams='http://127.0.0.1:{{ .Values.service.targetPort }}',access-log='/dev/stdout',inspect-websocket=true}"
        ports:
        - containerPort: {{ .Values.service.targetSigSciPort }}
        securityContext:
          # The sigsci-agent container should run with its root filesystem read only
          readOnlyRootFilesystem: true
        volumeMounts:
        # Default volume mount location for sigsci-agent writeable data
        # NOTE: Also change `SIGSCI_SHARED_CACHE_DIR` (default `/sigsci/tmp/cache`)
        #       if mountPath is changed, but best not to change.
        - name: sigsci-tmp
          mountPath: /sigsci/tmp
      {{- end }}
      volumes:
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-tmp
      {{- end }}
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment-api
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas.api }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr-api
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr-api
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
      - name: {{ .Values.secrets.existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      serviceAccountName: {{ template "qtest-chart.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountsatoken }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 300
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health-checker
            port: {{ .Values.service.targetPort }}
          failureThreshold: 60
          periodSeconds: 10
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: qtest-manager-config
        - secretRef:
            name: qtest-manager-secret
        env:
        {{- if .Values.env }}
{{- toYaml .Values.env | nindent 11 }}
        {{- end }}
           - name: testconductor.environment
             value: "api.production"
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-agent
        image: signalsciences/sigsci-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: SIGSCI_ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: accesskeyid
        - name: SIGSCI_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: sigsci-secret
              key: secretaccesskey
        # Configure the revproxy listener to listen on the original web application port 8000
        # forwarding to the app on the alternate port 8001 as the upstream
        - name: SIGSCI_REVPROXY_LISTENER
          value: "http:{listener='http://0.0.0.0:{{ .Values.service.targetSigSciPort }}',upstreams='http://127.0.0.1:{{ .Values.service.targetPort }}',access-log='/dev/stdout'}"
        ports:
        - containerPort: {{ .Values.service.targetSigSciPort }}
        securityContext:
          # The sigsci-agent container should run with its root filesystem read only
          readOnlyRootFilesystem: true
        volumeMounts:
        # Default volume mount location for sigsci-agent writeable data
        # NOTE: Also change `SIGSCI_SHARED_CACHE_DIR` (default `/sigsci/tmp/cache`)
        #       if mountPath is changed, but best not to change.
        - name: sigsci-tmp
          mountPath: /sigsci/tmp
      {{- end }}
      volumes:
      {{- if .Values.SigSci.enabled }}
      - name: sigsci-tmp
      {{- end }}
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}
