{{- if .Values.deployments.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgr-deployment
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: qtest-mgr
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qtest-mgr
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app: qtest-mgr
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      initContainers:
      - image: "{{ .Values.image.liquibase }}:{{ .Values.image.liquibasetag | default .Chart.AppVersion }}"
        name: qtestliquibase
        imagePullPolicy: {{ .Values.image.liquibasepullpolicy }}
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: qtest-manager-config
                key: qTestMgrClientjdbcPostgresUrl
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: qtest-manager-config
                key: qTestMgrClientjdbcPostgresUserName
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qtest-manager-secret
                key: qTestMgrClientjdbcPostgresPassword
      {{- if .Values.secrets.existingImageCredentials -}}
      imagePullSecrets:
      - name: {{ .Values.secrets.existingImageCredentials }}
      {{- else if .Values.imageCredentials.enabled -}}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        env:
        {{- if .Values.env }}
{{- toYaml .Values.env | nindent 11 }}
        {{- end }}
           - name: testconductor.environment
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrTestConductorEnvironment
           - name: spring.profiles.active
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrSpringProfilesActive
           - name: client.jdbc.postgres.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresUrl
           - name: client.jdbc.postgres.username
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresUserName
           - name: client.jdbc.postgres.password
             valueFrom:
               secretKeyRef:
                 name: qtest-manager-secret
                 key: qTestMgrClientjdbcPostgresPassword
           - name: client.jdbc.postgres.readonly.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresReadonlyUrl
           - name: client.jdbc.postgres.readonly.username
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrClientjdbcPostgresReadonlyUserName
           - name: client.jdbc.postgres.readonly.password
             valueFrom:
               secretKeyRef:
                 name: qtest-manager-secret
                 key: qTestMgrClientjdbcPostgresReadonlyPassword
           - name: elasticsearch.init
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchInit
           - name: elasticsearch.disable
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchDisable
           - name: elasticsearch.scheme
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchScheme
           - name: elasticsearch.host
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchHost
           - name: elasticsearch.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrElasticSearchPort
           - name: attachment.folder.path
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAttachmentFolderPath
           - name: search.folder.path
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrSearchFolderPath
           - name: license.folder.path
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrLicenseFolderPath
           - name: blobStorage.type
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageType
           - name: blobStorage.region
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageRegion
           - name: blobStorage.sharedBucket
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBlobStorageSharedBucket
           - name: s3.accessKey
             valueFrom:
               secretKeyRef:
                 name: qtest-manager-secret
                 key: qTestMgrS3AccessKey
           - name: s3.secretKey
             valueFrom:
               secretKeyRef:
                 name: qtest-manager-secret
                 key: qTestMgrS3SecretKey
           - name: s3.folder
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3Folder
           - name: s3.scan.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrS3ScanUrl
           - name: server.app.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerAppUrl
           - name: serverapp.useSecureCookie
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerAppUseSecureCookie
           - name: serverapp.ssl.required
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrServerAppSSLRequired
           - name: base.http.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBaseHttpPort
           - name: base.https.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrBaseHttpsPort
           - name: preUrl
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreUrl
           - name: preUrl.https
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreUrlHttps
           - name: qasymphonyUrlPostfix
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQasymphonyUrlPostfix
           - name: qas.directory.address
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQasDirectoryAddress
           - name: qTest.instance
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQTestInstance
           - name: qTest.app.version
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQTestAppVersion
           - name: app.name
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAppName
           - name: analytics.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrAnalyticsUrlBase
           - name: kafka.bootstrapAddress
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrKafkaBootstrapAddress
           - name: kafka.schemaRegistryUrl
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrKafkaSchemaRegistryUrl
           - name: pre.session.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPreSessionUrl
           - name: pulse.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrPulseUrlBase
           - name: insights.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrInsightsUrl
           - name: launch.url.base
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrLaunchUrlBase
           - name: notification.url.external
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrNotificationUrlExternal
           - name: notification.url.internal
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrNotificationUrlInternal
           - name: qtest.servermap.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrQtestServerMapUrl
           - name: report.http.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrReportHttpUrl
           - name: report.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrReportUrl
           - name: tdm.setting.url
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrTdmSettingUrl
           - name: mail.host
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailHost
           - name: mail.port
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailPort
           - name: mail.username
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailUserName
           - name: mail.password
             valueFrom:
               secretKeyRef:
                 name: qtest-manager-secret
                 key: qTestMgrMailPassword
           - name: mail.protocol
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailProtocol
           - name: mail.smtp.auth
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailSmtpAuth
           - name: mail.smtp.starttls.enable
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailSmtpTLS
           - name: supportEmailAddress
             valueFrom:
               configMapKeyRef:
                 name: qtest-manager-config
                 key: qTestMgrMailFromAddress
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: qtest-data
          mountPath: /mnt/data/storage
      volumes:
      - name: qtest-data
      {{- if .Values.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "qtest-chart.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}
