{{- if .Values.rollouts.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mgr-rollout
  labels:
    app: test-conductor
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-conductor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: test-conductor
        release: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: testconductor.environment
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrTestConductorEnvironment
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrSpringProfilesActive
            - name: client.jdbc.postgres.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrClientjdbcPostgresUrl
            - name: client.jdbc.postgres.username
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrClientjdbcPostgresUserName
            - name: client.jdbc.postgres.password
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: qTestMgrClientjdbcPostgresPassword
            - name: client.jdbc.postgres.readonly.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrClientjdbcPostgresReadonlyUrl
            - name: client.jdbc.postgres.readonly.username
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrClientjdbcPostgresReadonlyUserName
            - name: client.jdbc.postgres.readonly.password
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: qTestMgrClientjdbcPostgresReadonlyPassword
            - name: elasticsearch.init
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrElasticSearchInit
            - name: elasticsearch.disable
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrElasticSearchDisable
            - name: elasticsearch.scheme
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrElasticSearchScheme
            - name: elasticsearch.host
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrElasticSearchHost
            - name: elasticsearch.port
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrElasticSearchPort
            - name: attachment.folder.path
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrAttachmentFolderPath
            - name: search.folder.path
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrSearchFolderPath
            - name: license.folder.path
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrLicenseFolderPath
            - name: blobStorage.type
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrBlobStorageType
            - name: blobStorage.region
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrBlobStorageRegion
            - name: blobStorage.sharedBucket
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrBlobStorageSharedBucket
            - name: s3.accessKey
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: qTestMgrS3AccessKey
            - name: s3.secretKey
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: qTestMgrS3SecretKey
            - name: s3.folder
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrS3Folder
            - name: s3.scan.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrS3ScanUrl
            - name: server.app.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrServerAppUrl
            - name: serverapp.useSecureCookie
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrServerAppUseSecureCookie
            - name: serverapp.ssl.required
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrServerAppSSLRequired
            - name: base.http.port
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrBaseHttpPort
            - name: base.https.port
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrBaseHttpsPort
            - name: preUrl
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrPreUrl
            - name: preUrl.https
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrPreUrlHttps
            - name: qasymphonyUrlPostfix
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrQasymphonyUrlPostfix
            - name: qas.directory.address
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrQasDirectoryAddress
            - name: qTest.instance
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrQTestInstance
            - name: qTest.app.version
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrQTestAppVersion
            - name: app.name
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrAppName
            - name: analytics.url.base
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrAnalyticsUrlBase
            - name: kafka.bootstrapAddress
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrKafkaBootstrapAddress
            - name: kafka.schemaRegistryUrl
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrKafkaSchemaRegistryUrl
            - name: pre.session.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrPreSessionUrl
            - name: pulse.url.base
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrPulseUrlBase
            - name: insights.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrInsightsUrl
            - name: launch.url.base
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrLaunchUrlBase
            - name: notification.url.external
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrNotificationUrlExternal
            - name: notification.url.internal
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrNotificationUrlInternal
            - name: qtest.servermap.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrQtestServerMapUrl
            - name: report.http.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrReportHttpUrl
            - name: report.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrReportUrl
            - name: tdm.setting.url
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrTdmSettingUrl
            - name: mail.host
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrMailHost
            - name: mail.port
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrMailPort
            - name: mail.username
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrMailUserName
            - name: mail.password
              valueFrom:
                secretKeyRef:
                  name: qtest-manager-secret
                  key: qTestMgrMailPassword
            - name: mail.protocol
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrMailProtocol
            - name: mail.smtp.auth
              valueFrom:
                configMapKeyRef:
                  name: qtest-manager-config
                  key: qTestMgrMailSmtpAuth             
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  minReadySeconds: 30
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      canaryService: canary-{{ .Values.service.servicename }}
      stableService: {{ .Values.service.servicename }}
      trafficRouting:
        nginx:
          stableIngress: mgr-ingress
          annotationPrefix: nginx.ingress.kubernetes.io 
          {{- with .Values.ingress.canary.annotations }}
          additionalIngressAnnotations:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      steps:
      - setWeight: 20
      - analysis:
          templates:
          - templateName: success-rates
            clusterScope: true
          args:
          - name: service-name
      - setWeight: 50
      - pause: {}
{{- end }}
