{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: "{{ include "qtest-launch.fullname" . }}-ingressclass"
  namespace: {{ .Values.namespace.name }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefaultClass | quote }}
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
spec:
  controller: {{ .Values.ingressClass.controller }}
{{- end }}
