{{- if .Values.ingress.enabled -}}
{{- $paths := .Values.ingress.paths -}}
{{- $extraPaths := .Values.ingress.extraPaths -}}
{{- if semverCompare ">=1.18" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end}}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.labels }}
  labels:
  {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingressClass.enabled }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }} 
{{ else }}
  ingressClassName: "{{ include "qtest-session.fullname" . }}-ingressclass"
{{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.backendServiceName }}
                port: 
                  number: {{ $p.backendPort }}
  {{- end -}}
  {{- range $p := $extraPaths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.backendServiceName }}
                port:
                  number: {{ $p.backendPort }}
  {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.backendServiceName }}
                port: 
                  number: {{ $p.backendPort }}
  {{- end -}}
  {{- range $p := $extraPaths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.backendServiceName }}
                port:
                  number: {{ $p.backendPort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{ toYaml .Values.ingress.tls | nindent 4 }}
    {{- end -}}
  {{- end -}}
